pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./align-content.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; ALIGN-CONTENT","ALIGN CONTENT alinha as linhas do container em relação ao eixo vertical. Esta propriedade só funciona se existir mais de uma linha de flex-itens, ...",""],
["./align-items.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; ALIGN-ITEMS","ALIGN-ITEMS alinha os itens flex de acordo com o eixo secundário do container, é o inverso do eixo principal.",""],
["./align-self.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; ALIGN-SELF","ALIGN-SELF serve para definirmos o alinhamento específico de um único flex item dentro do nosso container. Caso seja atribuido um valor ele passar...",""],
["./combinadores.html","CSS &#62; COMBINADORES","Os combinadores atribuem a relação entre os seletores CSS, eles podem ser:",""],
["./custom-properties.html","CSS &#62; CUSTOM PROPERTIES","Para criar uma propriedade customizada (variável) em CSS é necessário fazer o seguinte:",""],
["./dicas-uteis.html","CSS &#62; DICAS UTEIS","UTILIZANDO O COUNTER PARA NUMERAR ITENS DENTRO DA PÁGINA:",""],
["./flex-basis.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; FLEX BASIS","FLEX BASIS indica o tamanho inicial do flex antes da distribuição do espaço restante. Quando definimos flex-grow: 1 e possuimos auto nos basis o v...",""],
["./flex-container.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER","FLEX CONTAINER é a tag (elemento, div, etc) que irá conter os items flex, ela é identificada com o comando css display: flex .",""],
["./flex-direction.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; FLEX-DIRECTION","FLEX DIRECTION define a direção dos itens flex, por padrão a direção é row (linha), por isso quando definimos o container para flex imediatamente ...",""],
["./flex-flow.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; FLEX-FLOW","FLEX FLOW é um shorthand (atalho) para os comandos flex direction e flex wrap, recomenda-se sempre que possível utilizar esta forma.",""],
["./flex-grow.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; FLEX-GROW","FLEX-GROW define a habilidade do item flex crescer. Por padrão esse valor é zero, assim os flex ocupam um tamanho máximo relacionado ao conteúdo i...",""],
["./flex-item.html","CSS &#62; FLEXBOX &#62; FLEX ITEM","FLEX ITEM são os filhos diretos do flex container, um item flex também pode ser um flex container.",""],
["./flex-items.html","CSS &#62; FLEXBOX &#62; FLEX ITEMS","FLEX ITEMS são os filhos que estão contidos dentro do flex container que foi criado. ",""],
["./flex-order.html","CSS &#62; FLEXBOX &#62; FLEX ORDER","Esta é uma propriedade que é aplicada nos itens do flex container.",""],
["./flex-shrink.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; FLEX-SHRINK","FLEX SHRINK define a habilidade de um item de reduzir o seu tamanho.",""],
["./flex-wrap.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; FLEX-WRAP","FLEX WRAP produz a quebra de linha quando os itens não couberem mais na tela. Para quebrar utilizamos a instrução flex-wrap: wrap ou flex-wrap: wr...",""],
["./flex.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; FLEX","FLEX atalho para as propriedades flex-grow, flex-shrink e flex-basis, ela é, e deve ser, mais utilizada que os valores em separado.",""],
["./flexbox.html","CSS &#62; FLEXBOX","Para utilizar flexbox precisamos ter uma div ou algo assim que possa conter todo o conteúdo para trabalhar, e este elemento deverá ser display:flex.",""],
["./git.html","GIT E GITHUB &#62; MANUAL GIT E GIT HUB","Git é um sistema de controle de versões distribuído, usado principalmente no desenvolvimento de software, mas pode ser usado para registrar o hist...",""],
["./introduction.html","CSS","Enter topic text here.asdfasdfasdf asd f as df a sdf  asdf  as df asdf asdf asdf",""],
["./justify-content.html","CSS &#62; FLEXBOX &#62; FLEX CONTAINER &#62; JUSTIFY-CONTENT","JUSTIFY-CONTENT é utilizado para alinhar os itens no eixo principal, no caso de row é um alinhamento horizontal, no caso de column é um alinhament...",""],
["./order.html","CSS &#62; FLEXBOX &#62; FLEX ITEM &#62; ORDER","ORDER modifica a ordem dos itens flex, sempre do menor para o maior.",""]];
